#!/usr/bin/env sh

USAGE="Usage: ${0} [-h] [-v] [command...]"

cd "$(dirname "${0}")" || exit 1

BREW_PREFIX=$(brew --prefix)
BINUTILS_PREFIX=$(brew --prefix binutils)
GCC_PREFIX=$(brew --prefix gcc)

CPATH="${BINUTILS_PREFIX}/include/:${BREW_PREFIX}/include/:${CPATH}"
export CPATH
LIBRARY_PATH="${BINUTILS_PREFIX}/lib/:${BREW_PREFIX}/lib/:${LIBRARY_PATH}"
export LIBRARY_PATH

verbose=0
opts=""
for opt in "${@}"
do
	if [ "${opt}" = "-h" ]
	then
		echo "${USAGE}"
		exit 0
	elif [ "${opt}" = "-v" ]
	then
		verbose=1
	else
		opts="${opts} ${opt}"
	fi
done

CXX="${GCC_PREFIX}/bin/g++-14 -B${BINUTILS_PREFIX}/bin"
export CXX

if [ ${verbose} = 1 ]
then
	export CXX="${CXX} -v"
fi

# shellcheck disable=SC2086
make ${opts}
